db: './db'

model:
  name: 'llama3.1'
  base_url: 'http://localhost:11434'
  temperature: 0
  num_ctx: 8192
  num_predict: 1536

history_size: 12

embedder: 'embed-multilingual-v3.0'
reranker: 'rerank-multilingual-v3.0'

retrieval_threshold: 0.7
followup_threshold: 0.45
distance_threshold: 0.2

k: 10 # standard retriever documents
top_n: 6 # compressor documents