db: './db'

model:
  name: 'Dolphin'
  base_url: 'http://localhost:11434'
  temperature: 0
  num_ctx: 8192
  num_predict: 1536

history_size: 12

embedder: 'embed-multilingual-v3.0'
reranker: 'rerank-multilingual-v3.0'

retrieval_threshold: 0.7
followup_threshold: 0.45
distance_threshold: 0.2

k: 10 # standard retriever documents
top_n: 6 # compressor documents

tts_model : "tts_models/multilingual/multi-dataset/xtts_v2"
speakers: ['Alexandra Hisakawa', 'Ana Florence', 'Asya Anara', 'Lilya Stainthorpe', 'Rosemary Okafor']
 
